// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: kronos.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkerState int32

const (
	WorkerState_IDLE WorkerState = 0
	WorkerState_BUSY WorkerState = 1
)

// Enum value maps for WorkerState.
var (
	WorkerState_name = map[int32]string{
		0: "IDLE",
		1: "BUSY",
	}
	WorkerState_value = map[string]int32{
		"IDLE": 0,
		"BUSY": 1,
	}
)

func (x WorkerState) Enum() *WorkerState {
	p := new(WorkerState)
	*p = x
	return p
}

func (x WorkerState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkerState) Descriptor() protoreflect.EnumDescriptor {
	return file_kronos_proto_enumTypes[0].Descriptor()
}

func (WorkerState) Type() protoreflect.EnumType {
	return &file_kronos_proto_enumTypes[0]
}

func (x WorkerState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkerState.Descriptor instead.
func (WorkerState) EnumDescriptor() ([]byte, []int) {
	return file_kronos_proto_rawDescGZIP(), []int{0}
}

type JobState int32

const (
	JobState_PENDING   JobState = 0
	JobState_ASSIGNED  JobState = 1
	JobState_RUNNING   JobState = 2
	JobState_SUCCEEDED JobState = 3
	JobState_FAILED    JobState = 4
)

// Enum value maps for JobState.
var (
	JobState_name = map[int32]string{
		0: "PENDING",
		1: "ASSIGNED",
		2: "RUNNING",
		3: "SUCCEEDED",
		4: "FAILED",
	}
	JobState_value = map[string]int32{
		"PENDING":   0,
		"ASSIGNED":  1,
		"RUNNING":   2,
		"SUCCEEDED": 3,
		"FAILED":    4,
	}
)

func (x JobState) Enum() *JobState {
	p := new(JobState)
	*p = x
	return p
}

func (x JobState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobState) Descriptor() protoreflect.EnumDescriptor {
	return file_kronos_proto_enumTypes[1].Descriptor()
}

func (JobState) Type() protoreflect.EnumType {
	return &file_kronos_proto_enumTypes[1]
}

func (x JobState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobState.Descriptor instead.
func (JobState) EnumDescriptor() ([]byte, []int) {
	return file_kronos_proto_rawDescGZIP(), []int{1}
}

type WorkerHeartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	CpuCores      int32                  `protobuf:"varint,2,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	MemoryMb      int64                  `protobuf:"varint,3,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	State         WorkerState            `protobuf:"varint,5,opt,name=state,proto3,enum=kronos.WorkerState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerHeartbeat) Reset() {
	*x = WorkerHeartbeat{}
	mi := &file_kronos_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerHeartbeat) ProtoMessage() {}

func (x *WorkerHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_kronos_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerHeartbeat.ProtoReflect.Descriptor instead.
func (*WorkerHeartbeat) Descriptor() ([]byte, []int) {
	return file_kronos_proto_rawDescGZIP(), []int{0}
}

func (x *WorkerHeartbeat) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *WorkerHeartbeat) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *WorkerHeartbeat) GetMemoryMb() int64 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *WorkerHeartbeat) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *WorkerHeartbeat) GetState() WorkerState {
	if x != nil {
		return x.State
	}
	return WorkerState_IDLE
}

type JobSpec struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Command string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Args    []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	Env     map[string]string      `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// resource requirements
	RequireCpuCores int32             `protobuf:"varint,4,opt,name=require_cpu_cores,json=requireCpuCores,proto3" json:"require_cpu_cores,omitempty"`
	RequireMemoryMb int64             `protobuf:"varint,5,opt,name=require_memory_mb,json=requireMemoryMb,proto3" json:"require_memory_mb,omitempty"`
	LabelSelectors  map[string]string `protobuf:"bytes,6,rep,name=label_selectors,json=labelSelectors,proto3" json:"label_selectors,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *JobSpec) Reset() {
	*x = JobSpec{}
	mi := &file_kronos_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobSpec) ProtoMessage() {}

func (x *JobSpec) ProtoReflect() protoreflect.Message {
	mi := &file_kronos_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobSpec.ProtoReflect.Descriptor instead.
func (*JobSpec) Descriptor() ([]byte, []int) {
	return file_kronos_proto_rawDescGZIP(), []int{1}
}

func (x *JobSpec) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *JobSpec) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *JobSpec) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *JobSpec) GetRequireCpuCores() int32 {
	if x != nil {
		return x.RequireCpuCores
	}
	return 0
}

func (x *JobSpec) GetRequireMemoryMb() int64 {
	if x != nil {
		return x.RequireMemoryMb
	}
	return 0
}

func (x *JobSpec) GetLabelSelectors() map[string]string {
	if x != nil {
		return x.LabelSelectors
	}
	return nil
}

type JobReceipt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobReceipt) Reset() {
	*x = JobReceipt{}
	mi := &file_kronos_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobReceipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobReceipt) ProtoMessage() {}

func (x *JobReceipt) ProtoReflect() protoreflect.Message {
	mi := &file_kronos_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobReceipt.ProtoReflect.Descriptor instead.
func (*JobReceipt) Descriptor() ([]byte, []int) {
	return file_kronos_proto_rawDescGZIP(), []int{2}
}

func (x *JobReceipt) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type JobAssignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Args          []string               `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	Env           map[string]string      `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobAssignment) Reset() {
	*x = JobAssignment{}
	mi := &file_kronos_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobAssignment) ProtoMessage() {}

func (x *JobAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_kronos_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobAssignment.ProtoReflect.Descriptor instead.
func (*JobAssignment) Descriptor() ([]byte, []int) {
	return file_kronos_proto_rawDescGZIP(), []int{3}
}

func (x *JobAssignment) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobAssignment) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *JobAssignment) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *JobAssignment) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

type JobResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Output        string                 `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobResult) Reset() {
	*x = JobResult{}
	mi := &file_kronos_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobResult) ProtoMessage() {}

func (x *JobResult) ProtoReflect() protoreflect.Message {
	mi := &file_kronos_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobResult.ProtoReflect.Descriptor instead.
func (*JobResult) Descriptor() ([]byte, []int) {
	return file_kronos_proto_rawDescGZIP(), []int{4}
}

func (x *JobResult) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *JobResult) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *JobResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ResultAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultAck) Reset() {
	*x = ResultAck{}
	mi := &file_kronos_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultAck) ProtoMessage() {}

func (x *ResultAck) ProtoReflect() protoreflect.Message {
	mi := &file_kronos_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultAck.ProtoReflect.Descriptor instead.
func (*ResultAck) Descriptor() ([]byte, []int) {
	return file_kronos_proto_rawDescGZIP(), []int{5}
}

type JobStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobStatusRequest) Reset() {
	*x = JobStatusRequest{}
	mi := &file_kronos_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStatusRequest) ProtoMessage() {}

func (x *JobStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kronos_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStatusRequest.ProtoReflect.Descriptor instead.
func (*JobStatusRequest) Descriptor() ([]byte, []int) {
	return file_kronos_proto_rawDescGZIP(), []int{6}
}

func (x *JobStatusRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type JobStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	State         JobState               `protobuf:"varint,2,opt,name=state,proto3,enum=kronos.JobState" json:"state,omitempty"`
	WorkerId      string                 `protobuf:"bytes,3,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Output        string                 `protobuf:"bytes,4,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobStatus) Reset() {
	*x = JobStatus{}
	mi := &file_kronos_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStatus) ProtoMessage() {}

func (x *JobStatus) ProtoReflect() protoreflect.Message {
	mi := &file_kronos_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStatus.ProtoReflect.Descriptor instead.
func (*JobStatus) Descriptor() ([]byte, []int) {
	return file_kronos_proto_rawDescGZIP(), []int{7}
}

func (x *JobStatus) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobStatus) GetState() JobState {
	if x != nil {
		return x.State
	}
	return JobState_PENDING
}

func (x *JobStatus) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *JobStatus) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *JobStatus) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_kronos_proto protoreflect.FileDescriptor

const file_kronos_proto_rawDesc = "" +
	"\n" +
	"\fkronos.proto\x12\x06kronos\"\x8b\x02\n" +
	"\x0fWorkerHeartbeat\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1b\n" +
	"\tcpu_cores\x18\x02 \x01(\x05R\bcpuCores\x12\x1b\n" +
	"\tmemory_mb\x18\x03 \x01(\x03R\bmemoryMb\x12;\n" +
	"\x06labels\x18\x04 \x03(\v2#.kronos.WorkerHeartbeat.LabelsEntryR\x06labels\x12)\n" +
	"\x05state\x18\x05 \x01(\x0e2\x13.kronos.WorkerStateR\x05state\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x84\x03\n" +
	"\aJobSpec\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\x12*\n" +
	"\x03env\x18\x03 \x03(\v2\x18.kronos.JobSpec.EnvEntryR\x03env\x12*\n" +
	"\x11require_cpu_cores\x18\x04 \x01(\x05R\x0frequireCpuCores\x12*\n" +
	"\x11require_memory_mb\x18\x05 \x01(\x03R\x0frequireMemoryMb\x12L\n" +
	"\x0flabel_selectors\x18\x06 \x03(\v2#.kronos.JobSpec.LabelSelectorsEntryR\x0elabelSelectors\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aA\n" +
	"\x13LabelSelectorsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"#\n" +
	"\n" +
	"JobReceipt\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\xbe\x01\n" +
	"\rJobAssignment\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\x120\n" +
	"\x03env\x18\x04 \x03(\v2\x1e.kronos.JobAssignment.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"j\n" +
	"\tJobResult\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x16\n" +
	"\x06output\x18\x03 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\v\n" +
	"\tResultAck\")\n" +
	"\x10JobStatusRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\x95\x01\n" +
	"\tJobStatus\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12&\n" +
	"\x05state\x18\x02 \x01(\x0e2\x10.kronos.JobStateR\x05state\x12\x1b\n" +
	"\tworker_id\x18\x03 \x01(\tR\bworkerId\x12\x16\n" +
	"\x06output\x18\x04 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error*!\n" +
	"\vWorkerState\x12\b\n" +
	"\x04IDLE\x10\x00\x12\b\n" +
	"\x04BUSY\x10\x01*M\n" +
	"\bJobState\x12\v\n" +
	"\aPENDING\x10\x00\x12\f\n" +
	"\bASSIGNED\x10\x01\x12\v\n" +
	"\aRUNNING\x10\x02\x12\r\n" +
	"\tSUCCEEDED\x10\x03\x12\n" +
	"\n" +
	"\x06FAILED\x10\x042\xef\x01\n" +
	"\tScheduler\x12=\n" +
	"\aConnect\x12\x17.kronos.WorkerHeartbeat\x1a\x15.kronos.JobAssignment(\x010\x01\x120\n" +
	"\tSubmitJob\x12\x0f.kronos.JobSpec\x1a\x12.kronos.JobReceipt\x124\n" +
	"\fReportResult\x12\x11.kronos.JobResult\x1a\x11.kronos.ResultAck\x12;\n" +
	"\fGetJobStatus\x12\x18.kronos.JobStatusRequest\x1a\x11.kronos.JobStatusB\x0eZ\fkronos/protob\x06proto3"

var (
	file_kronos_proto_rawDescOnce sync.Once
	file_kronos_proto_rawDescData []byte
)

func file_kronos_proto_rawDescGZIP() []byte {
	file_kronos_proto_rawDescOnce.Do(func() {
		file_kronos_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kronos_proto_rawDesc), len(file_kronos_proto_rawDesc)))
	})
	return file_kronos_proto_rawDescData
}

var file_kronos_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_kronos_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_kronos_proto_goTypes = []any{
	(WorkerState)(0),         // 0: kronos.WorkerState
	(JobState)(0),            // 1: kronos.JobState
	(*WorkerHeartbeat)(nil),  // 2: kronos.WorkerHeartbeat
	(*JobSpec)(nil),          // 3: kronos.JobSpec
	(*JobReceipt)(nil),       // 4: kronos.JobReceipt
	(*JobAssignment)(nil),    // 5: kronos.JobAssignment
	(*JobResult)(nil),        // 6: kronos.JobResult
	(*ResultAck)(nil),        // 7: kronos.ResultAck
	(*JobStatusRequest)(nil), // 8: kronos.JobStatusRequest
	(*JobStatus)(nil),        // 9: kronos.JobStatus
	nil,                      // 10: kronos.WorkerHeartbeat.LabelsEntry
	nil,                      // 11: kronos.JobSpec.EnvEntry
	nil,                      // 12: kronos.JobSpec.LabelSelectorsEntry
	nil,                      // 13: kronos.JobAssignment.EnvEntry
}
var file_kronos_proto_depIdxs = []int32{
	10, // 0: kronos.WorkerHeartbeat.labels:type_name -> kronos.WorkerHeartbeat.LabelsEntry
	0,  // 1: kronos.WorkerHeartbeat.state:type_name -> kronos.WorkerState
	11, // 2: kronos.JobSpec.env:type_name -> kronos.JobSpec.EnvEntry
	12, // 3: kronos.JobSpec.label_selectors:type_name -> kronos.JobSpec.LabelSelectorsEntry
	13, // 4: kronos.JobAssignment.env:type_name -> kronos.JobAssignment.EnvEntry
	1,  // 5: kronos.JobStatus.state:type_name -> kronos.JobState
	2,  // 6: kronos.Scheduler.Connect:input_type -> kronos.WorkerHeartbeat
	3,  // 7: kronos.Scheduler.SubmitJob:input_type -> kronos.JobSpec
	6,  // 8: kronos.Scheduler.ReportResult:input_type -> kronos.JobResult
	8,  // 9: kronos.Scheduler.GetJobStatus:input_type -> kronos.JobStatusRequest
	5,  // 10: kronos.Scheduler.Connect:output_type -> kronos.JobAssignment
	4,  // 11: kronos.Scheduler.SubmitJob:output_type -> kronos.JobReceipt
	7,  // 12: kronos.Scheduler.ReportResult:output_type -> kronos.ResultAck
	9,  // 13: kronos.Scheduler.GetJobStatus:output_type -> kronos.JobStatus
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_kronos_proto_init() }
func file_kronos_proto_init() {
	if File_kronos_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kronos_proto_rawDesc), len(file_kronos_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kronos_proto_goTypes,
		DependencyIndexes: file_kronos_proto_depIdxs,
		EnumInfos:         file_kronos_proto_enumTypes,
		MessageInfos:      file_kronos_proto_msgTypes,
	}.Build()
	File_kronos_proto = out.File
	file_kronos_proto_goTypes = nil
	file_kronos_proto_depIdxs = nil
}
